//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLamarelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public int ID { get; set; }
        public Nullable<int> Niveau { get; set; }
        public string Nom { get; set; }
        public string Enseignant { get; set; }
        public Nullable<int> AgeDebut { get; set; }
        public Nullable<int> AgeFin { get; set; }
        public string Section { get; set; }
        public decimal Heures { get; set; }
    }
}
