//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLamarelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_contacts
    {
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Adresse1 { get; set; }
        public string Adresse2 { get; set; }
        public string Adresse3 { get; set; }
        public string Ville { get; set; }
        public string Code_Postal { get; set; }
        public string Fixe { get; set; }
        public string Portable { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> ActuellementInscrit { get; set; }
        public Nullable<bool> Comite { get; set; }
        public Nullable<bool> NePasContacter { get; set; }
    }
}
