//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLamarelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class eleve
    {
        public int ID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public string Nationalite { get; set; }
        public Nullable<System.DateTime> PremiereRentree { get; set; }
        public string ClasseActuelle { get; set; }
        public Nullable<bool> ActuellementInscrit { get; set; }
        public Nullable<bool> PreInscrit { get; set; }
        public string Sexe { get; set; }
        public string RelationAutreParent { get; set; }
        public string NomAutreParent { get; set; }
        public string PrenomAutreParent { get; set; }
        public string AdresseAutreParent { get; set; }
        public string FixeAutreParent { get; set; }
        public string PortableAutreParent { get; set; }
        public string EmailAutreParent { get; set; }
        public string Docteur { get; set; }
        public Nullable<bool> PhotosClasse { get; set; }
        public Nullable<bool> PhotosWeb { get; set; }
        public Nullable<bool> Gateaux { get; set; }
        public Nullable<bool> PbMedicaux { get; set; }
        public string DetailsMedicaux { get; set; }
    }
}
