//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLamarelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentree
    {
        public Nullable<System.DateTime> Rentree1 { get; set; }
        public Nullable<System.DateTime> DernierCours { get; set; }
        public int ID { get; set; }
    }
}
